daysUntilClose: 180
responseRequiredLabel: more-information-needed
closeComment: >
  This issue has been automatically closed because there has been no response
  to our request for more information from the original author. With only the
  information that is currently in the issue, we don't have enough information
  to take action or reproduce the issue. Please reach out if you have or find
  the answers we need so that we can investigate further.
