SETTING_FILENAME = 'filename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_PAINT_LABEL = 'paintlabel'
SETTING_LAST_OPEN_DIR = 'lastOpenDir'
SETTING_AUTO_SAVE = 'autosave'
SETTING_SINGLE_CLASS = 'singleclass'
FORMAT_PASCALVOC='PascalVOC'
FORMAT_YOLO='YOLO'
FORMAT_CREATEML='CreateML'
SETTING_DRAW_SQUARE = 'draw/square'
SETTING_LABEL_FILE_FORMAT= 'labelFileFormat'
DEFAULT_ENCODING = 'utf-8'

# DEFINE COLORS
from PyQt5.QtGui import *
CLASS_COLOR_0 = QColor(0, 0, 255, 255)
CLASS_COLOR_1 = QColor(153, 51, 255, 255)
DRAWING_COLOR = QColor(0, 0, 0)
BACKGROUND_COLOR = QColor(0, 0, 0, 200)

HOVER_COLOR = QColor(106, 180, 255, 125)
VERTEX_FILL_COLOR = QColor(0, 0, 0, 0)

